__author__ = 'v-iganoh'

from vegenere import Vegenere
from kassiski import Kassiski


print 'compute'

ks = Kassiski()
krypto = 'JJLOLGOSZIWRVYHMWTVMBIXVNJFKXBYFWOKYOHNRYMGXDZMXMTTRNLZTAGAXYHAKRXYBAOHASJXZXXIZKOYRXJJANKKRXTYLTTFGYMKWPNNVNBTEFGGIOKWLGWRSFRAXXZMXYDLZJFSTWKWGIWRVYHMWTVMRNFLLTVAXXJTGHZBRIBTLTYTNTIYUZGJFMOTGZTTIMBKAXZMBYLHGQBTUTXYBIZEGWMNJHTQRGXLARIZNHTRTJJTHTNZFGGIOKWLGWROXBZXVURIAYTZNHTFEGGBRNMEYRVNVGQEETGKFLYZFKXMNJTJAXXXTXDAGXTIQTYXBIFEITFVZMKWTTIBYWXYYKOHMKIMUWTTIHSNSKIIUQRTTFOFEZNFKGNZNYUSXTTPGXLARXYYAGYMNJTJAXXXTXDAGXTWZTTYNSHHSUNZJKZMXTBAOHAIQTYXBIFEIWRVYHYDLZJFYFKKXXIZKKFGJBAOHAGWXTTMWZTTYNSHHSUNZFMOTGAXXYWNRJLCMBIMTXJGKBTTINTNGZZBZNOKXHSJLAGKUZMOSXYXNIMTYHHSUNZNGMYAKVNGSMARYUZKOJKZWTTXYUWFIFGHJIKWYUWFKIXDUHTJGZNTRQRLFLZJKZMTTGRIQTYXBIFEITFVZMKWLNTPKAXXYAOXBYSHZKHXKKKJMNJFKYAUILZTBTUNZFGJTNZUNZYAKITZFYXTFZMXLTNXNXXYKGSLLTKSFKKAXXDKKXMXNVZJWNJGIJYOSWOSZWZTTYNSFEMTKOYASXKKQBKXHTBTRPBTLTLNGKQBTJUKYPKJGAXBTLXDYKGUHCJKCMBRJUKNGMQBSNMKIBTXHSJBSUHXYTTYPGDL'
keys = ks.compute(krypto, 3, 5)

veg = Vegenere()
for index in keys:
    print ''
    print '****'
    print 'Key: %s' % keys[index]
    plain_text = veg.decrypt(krypto, keys[index])
    print 'Text: '
    print plain_text
    print '****'
