__author__ = 'v-iganoh'


part_one = 'JOOIVMVINKYOORGZMRZGYKYOSZIOXAKTTGKNNEGKGSAZYZSKIVMVNLAJHRTYTUJOZIKZYGTXIGNTGAZTJHZGKGOZUAZTGREVGEKYKNJXXGIYIIVKTYYOKUTSKUTOZKZUTGAYGNJXXGWTSSZZTOIYIIVYZYKIKJOGTWTSSZOAYRCIXKTTZZKSAUOYIYSZMKGAUOZTUIHKUKDTZRLZZTIYIIVKNKXOYZXKNKUZTZJZZKZXZLXXGLSKXKXZNIOOWTSMOSKKTRTLKTKKATDGCCRKMSKTSSXTG'
part_two = 'JLSWYWMXJXFKHYXMTNTAHRBHJXZYJNRYTYWNBFIWWFXMDJTWWYWMFTXTZILTIZFTTMAMLQUYZWJQXRNRJTFIWWXXRYNFGNYNQTFZXJAXDXQXFTZWIWYHIWINIQTFNGNSTXRYYJAXDXZYHUJMBHQXFWYDJFXZFBHWTZYHUFTXWJMMJBINZNXJGZSXMHUNYVSRZJWXWFJWWIUJNQFJMGQXFTZWTAYXSKKJJYITUFTUYIFTMTNYSTFADXNJJJSSZYFTYXQXBPLNQJYJXLYUJMJNQNIXJUYYD'
part_three = 'LGZRHTBVFBWYNMDXTLAXAXAAXXKRJKXLFMPVTGOLRRXXLFWGRHTRLVXGBBTNYGMGTBXBHBTBEMHRLIHTTNGOLRBVITHEBMRVEGLFMTXTATTBEFMTBXKMMTHSIRFEFNYXPLXAMTXTATTNHNKXAATBERHLFKXKGAAXMTNHNMGXNLBTGTNGBOHLKMXNTHNGANMYKKTYFGIYFXHGTRLKTRTBEFMLPXABHHKMFALBNGNNATYFXNXKLKKXKMVWGYWZTNEKAKBHTBTGBUPGBXKHKBUGBMBHBHTPL'

def get_frequencies_with_percentage_array(text):
    char_frequencies = {}
    for index, char in enumerate(text):
        #char = unichr(ord(char) - 65)
        char = ord(char) - 65
        if char in char_frequencies:
            char_frequencies[char] += 1
        else:
            char_frequencies[char] = 1

    freq_with_percent = {}
    for key in char_frequencies:
        val = char_frequencies[key]
        freq_with_percent[key] = {val: '%0.2f%%' % (float(val) / float(len(part_one)) * 100)}

    return freq_with_percent

def get_frequencies(text):
    frequencies = [0 for i in range(26)]
    for index, char in enumerate(text):
        frequencies[ord(char) - 65] += 1

    return frequencies

print get_frequencies(part_one)
print get_frequencies_with_percentage_array(part_one)
print unichr((10 - 4) + 65) # G {35: '12.28'}
print unichr((25 - 4) + 65) # V {32: '10.18'}
print ''
print get_frequencies(part_two)
print get_frequencies_with_percentage_array(part_two)
print unichr((23 - 4) + 65) # T {29: '10.18'}
print unichr((9 - 4) + 65)  # F {28: '9.82'}

print ''
print get_frequencies(part_three)
print get_frequencies_with_percentage_array(part_three)
print unichr((19 - 4) + 65) # P {34: '11.93'}
print unichr((23 - 4) + 65) # T {26: '9.12'}
print ''

# 'GFT'
# 'GTP'

from vegenere import Vegenere
krypto = 'JJLOLGOSZIWRVYHMWTVMBIXVNJFKXBYFWOKYOHNRYMGXDZMXMTTRNLZTAGAXYHAKRXYBAOHASJXZXXIZKOYRXJJANKKRXTYLTTFGYMKWPNNVNBTEFGGIOKWLGWRSFRAXXZMXYDLZJFSTWKWGIWRVYHMWTVMRNFLLTVAXXJTGHZBRIBTLTYTNTIYUZGJFMOTGZTTIMBKAXZMBYLHGQBTUTXYBIZEGWMNJHTQRGXLARIZNHTRTJJTHTNZFGGIOKWLGWROXBZXVURIAYTZNHTFEGGBRNMEYRVNVGQEETGKFLYZFKXMNJTJAXXXTXDAGXTIQTYXBIFEITFVZMKWTTIBYWXYYKOHMKIMUWTTIHSNSKIIUQRTTFOFEZNFKGNZNYUSXTTPGXLARXYYAGYMNJTJAXXXTXDAGXTWZTTYNSHHSUNZJKZMXTBAOHAIQTYXBIFEIWRVYHYDLZJFYFKKXXIZKKFGJBAOHAGWXTTMWZTTYNSHHSUNZFMOTGAXXYWNRJLCMBIMTXJGKBTTINTNGZZBZNOKXHSJLAGKUZMOSXYXNIMTYHHSUNZNGMYAKVNGSMARYUZKOJKZWTTXYUWFIFGHJIKWYUWFKIXDUHTJGZNTRQRLFLZJKZMTTGRIQTYXBIFEITFVZMKWLNTPKAXXYAOXBYSHZKHXKKKJMNJFKYAUILZTBTUNZFGJTNZUNZYAKITZFYXTFZMXLTNXNXXYKGSLLTKSFKKAXXDKKXMXNVZJWNJGIJYOSWOSZWZTTYNSFEMTKOYASXKKQBKXHTBTRPBTLTLNGKQBTJUKYPKJGAXBTLXDYKGUHCJKCMBRJUKNGMQBSNMKIBTXHSJBSUHXYTTYPGDL'
veg = Vegenere()
plain1 = veg.decrypt(krypto, 'GFT')
print plain1
plain2 = veg.decrypt(part_one, 'GTP')
print plain2
print ''
